
package view;

import controller.MenuUsuarioController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import model.Usuario;
import model.Utilitarios;

/**
 *
 * @author C2testenovo
 */
public class FuncionarioView extends javax.swing.JFrame {

    private final MenuUsuarioController controller;
    Usuario usuarioLogado = new Usuario();
    UsuarioPanel usuarioPane = new UsuarioPanel();
    PrincipalMenuPane menuPrincipal = new PrincipalMenuPane();
    ProdutoPane produtoPane = new ProdutoPane();
    ClientePane clientePane = new ClientePane();
    HistoricoPane historicoPane = new HistoricoPane();
    VendaPane vendaPane = new VendaPane();
    public String cpf;
    
    public FuncionarioView() {
        
        initComponents();
        this.setSize(1920,1080);//resolução do monitor
        this.setLocationRelativeTo(null);
        
        MainPane.add(usuarioPane);
        MainPane.add(menuPrincipal);
        MainPane.add(produtoPane);
        MainPane.add(clientePane);
        MainPane.add(historicoPane);
        MainPane.add(vendaPane);
        
        controller = new MenuUsuarioController(this);
        controller.menuPrincipal();   
        
        Utilitarios u = new Utilitarios();
        u.InserirIcone(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoAbrirPaneVenda = new javax.swing.JButton();
        BotaoAbrirPaneProdutos = new javax.swing.JButton();
        BotaoAbrirPaneHome = new javax.swing.JButton();
        MainPane = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        BotaoAbrirPaneVenda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotaoAbrirPaneVenda.setText("Iniciar uma Venda");
        BotaoAbrirPaneVenda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotaoAbrirPaneVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAbrirPaneVendaActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAbrirPaneVenda);
        BotaoAbrirPaneVenda.setBounds(80, 70, 150, 37);

        BotaoAbrirPaneProdutos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotaoAbrirPaneProdutos.setText("Produtos");
        BotaoAbrirPaneProdutos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotaoAbrirPaneProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAbrirPaneProdutosActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAbrirPaneProdutos);
        BotaoAbrirPaneProdutos.setBounds(80, 110, 150, 36);

        BotaoAbrirPaneHome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotaoAbrirPaneHome.setText("Home");
        BotaoAbrirPaneHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotaoAbrirPaneHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAbrirPaneHomeActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAbrirPaneHome);
        BotaoAbrirPaneHome.setBounds(80, 30, 150, 37);

        MainPane.setMinimumSize(null);
        MainPane.setLayout(new java.awt.CardLayout());
        getContentPane().add(MainPane);
        MainPane.setBounds(310, 30, 1570, 940);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    
    public ClientePane getClientePane() {
        return clientePane;
    }

    public void setClientePane(ClientePane clientePane) {
        this.clientePane = clientePane;
    }

    public UsuarioPanel getUsuarioPane() {
        return usuarioPane;
    }

    public void setUsuarioPane(UsuarioPanel usuarioPane) {
        this.usuarioPane = usuarioPane;
    }

    public PrincipalMenuPane getMenuPrincipal() {
        return menuPrincipal;
    }

    public void setMenuPrincipal(PrincipalMenuPane menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }

    public ProdutoPane getProdutoPane() {
        return produtoPane;
    }

    public void setProdutoPane(ProdutoPane produtoPane) {
        this.produtoPane = produtoPane;
    }
    
    public HistoricoPane getHistoricoPane() {
        return historicoPane;
    }

    public void setHistoricoPane(HistoricoPane HistoricoPane) {
        this.historicoPane = historicoPane;
    }
    
    public VendaPane getVendaPane() {
        return vendaPane;
    }

    public void setVendaPane(VendaPane vendaPane) {
        this.vendaPane = vendaPane;
    }

    public Usuario getUsuarioLogado() {
        return usuarioLogado;
    }

    public void setUsuarioLogado(Usuario usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
        getMenuPrincipal().getLabelNomeUsuarioLogado().setText("Olá! " + usuarioLogado.getNome());
    }
    
    private void BotaoAbrirPaneHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAbrirPaneHomeActionPerformed
        controller.menuPrincipal();
    }//GEN-LAST:event_BotaoAbrirPaneHomeActionPerformed

    private void BotaoAbrirPaneVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAbrirPaneVendaActionPerformed
        vendaPane.setCpf(this.cpf);
        controller.vendaPane();
    }//GEN-LAST:event_BotaoAbrirPaneVendaActionPerformed

    private void BotaoAbrirPaneProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAbrirPaneProdutosActionPerformed
        controller.produtoPane();
    }//GEN-LAST:event_BotaoAbrirPaneProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAbrirPaneHome;
    private javax.swing.JButton BotaoAbrirPaneProdutos;
    private javax.swing.JButton BotaoAbrirPaneVenda;
    private javax.swing.JLayeredPane MainPane;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    
}
