/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JLabel;
import model.Usuario;

/**
 *
 * @author luizf
 */
public class PrincipalMenuPane extends javax.swing.JPanel {

    public PrincipalMenuPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNomeUsuarioLogado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelNomeUsuarioLogado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LabelNomeUsuarioLogado.setForeground(new java.awt.Color(255, 255, 255));
        LabelNomeUsuarioLogado.setText("nulo");
        add(LabelNomeUsuarioLogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 31, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(1651, 1086));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -13, -1, 1100));
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLabelNomeUsuarioLogado() {
        return LabelNomeUsuarioLogado;
    }

    public void setLabelNomeUsuarioLogado(JLabel LabelNomeUsuarioLogado) {
        this.LabelNomeUsuarioLogado = LabelNomeUsuarioLogado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNomeUsuarioLogado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
