/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JLabel;
import model.Usuario;

/**
 *
 * @author luizf
 */
public class PrincipalMenuPane extends javax.swing.JPanel {

    public PrincipalMenuPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNomeUsuarioLogado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        LabelNomeUsuarioLogado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LabelNomeUsuarioLogado.setText("nulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(LabelNomeUsuarioLogado)
                .addContainerGap(1539, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LabelNomeUsuarioLogado)
                .addContainerGap(1007, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLabelNomeUsuarioLogado() {
        return LabelNomeUsuarioLogado;
    }

    public void setLabelNomeUsuarioLogado(JLabel LabelNomeUsuarioLogado) {
        this.LabelNomeUsuarioLogado = LabelNomeUsuarioLogado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNomeUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
